[package]
name = "shalem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bevy_egui = { version = "0.24.0", features = ["immutable_ctx"] }
egui = "0.24.0"